### ISSUE TITLE
Errore installazioni dipendenze

### ISSUE THREAD

**Issue by chemickypes** [WhiteLabelCommunity/whitelabel-slides-template#11]
Ragazzi, sto provando a buildare il tutto per fare le slide, ma si vede che non sono un frontend developer perché ottengo questo errore. Sapete dirmi?

```
whitelabel-slides-template|develop ⇒ yarn
yarn install v1.16.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > gatsby-transformer-remark@2.3.8" has incorrect peer dependency "gatsby@^2.0.88".
warning " > react-inlinesvg@0.8.4" has unmet peer dependency "prop-types@^15.0.0".
[4/4] 🔨  Building fresh packages...
[1/6] ⠈ fsevents
[2/6] ⠈ node-sass
[6/6] ⠈ sharp
[-/6] ⠈ waiting...
warning Error running install script for optional dependency: "/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@12.3.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.3.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/.node-gyp/12.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/angelomoroni/.node-gyp/12.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/angelomoroni/.node-gyp/12.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:51:
/Users/angelomoroni/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: 'util-inl.h' file not found
#  include <util-inl.h>
           ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command \"/Users/angelomoroni/.nvm/versions/node/v12.3.0/bin/node\" \"/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/angelomoroni/.nvm/versions/node/v12.3.0/bin/node /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command \"/Users/angelomoroni/.nvm/versions/node/v12.3.0/bin/node\" \"/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents
node-pre-gyp ERR! node -v v12.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/angelomoroni/.nvm/versions/node/v12.3.0/bin/node /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse -[-/6] ⡀ waiting...
[2/6] ⡀ node-sass
[6/6] ⡀ sharp
[-/6] ⡀ waiting...
error /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/sharp
Output:
info sharp Using cached /Users/angelomoroni/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.3.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/angelomoroni/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/angelomoroni/.node-gyp/12.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/angelomoroni/.node-gyp/12.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/angelomoroni/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/angelomoroni/.node-gyp/12.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:22:
/Users/angelomoroni/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: 'util-inl.h' file not found
#  include <util-inl.h>
           ^
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/angelomoroni/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/angelomoroni/.nvm/versions/node/v12.3.0/bin/node" "/Users/angelomoroni/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/angelomoroni/Programmazione/white_label_slides/whitelabel-slides-template/node_modules/sharp
gyp ERR! node -v v12.3.0
```

**Comment by storrisi** [comment]
Devi usare una versione di node >= 10.15.3 , puoi aggiornarla usando nvm

**Comment by chemickypes** [comment]
Questa è la versione di npm che ho installato
```
whitelabel-slides-template|develop ⇒ npm -v
6.9.0
```

**Comment by chemickypes** [comment]
Node:
```
whitelabel-slides-template|develop ⇒ node --version
v12.3.0
```

**Comment by storrisi** [comment]
Fai un downgrade all'ultima stable di node, ti conviene

Probabilmente alcune funzioni non sono supportate

**Comment by chemickypes** [comment]
Risolto usando la versione 10.15.3 di node
